modmap:
  - name: Caps lock acts as control, caps lock and alt act as a prefix and as compose when pressed alone, respectively
    remap:
      KEY_RIGHTALT:
        held: ALT_R
        alone: Compose
        alone_timeout_millis: 500
      CapsLock:
        held: CTRL_R
        alone: ALT-F1
        alone_timeout_millis: 500

keymap:
  - name: Caps lock as prefix key, mostly for hyprland bindings
    mode: default
    remap:
      # CTRL_R-KEY_J: Esc

      ALT-F1:
        remap:
          # ALT-F1: CTRL-ALT-Esc
          #   launch: ["zsh", "$HOME/.local/sbin/toggle_caps_led"]
          KEY_B: ALT-KEY_A  # Tmux
          Apostrophe: SUPER-KEY_Q # Go to terminal
          KEY_I: ALT-KEY_I  # Go to terminal and lock
          Semicolon: ALT-Semicolon  # Go to terminal and unlock
          KEY_O: SUPER-KEY_W  # Go to browser
          KEY_P: SUPER-ALT_W  # Browser in empty workspace
          KEY_R: SUPER-KEY_R  # Runner in empty workspace
          KEY_T: SUPER-KEY_T  # Runner in current workspace

          # Window movement
          KEY_H: SUPER-KEY_H
          KEY_J: SUPER-KEY_J
          KEY_K: SUPER-KEY_K
          KEY_L: SUPER-KEY_L

          KEY_U: ALT-KEY_Q  # Zellij
        timeout_millis: 500

  - name:
    application:
      only: Firefox
    remap:
      # Arrow keys for scrolling
      CTRL_R-KEY_H: Left
      CTRL_R-KEY_J: Down
      CTRL_R-KEY_K: Up
      CTRL_R-KEY_L: Right

  - name:
    application:
      only: Discord
    remap:
      CTRL_R-KEY_H: CTRL-SHIFT-Tab
      CTRL_R-KEY_J: ALT-Down
      CTRL_R-KEY_K: ALT-Up
      CTRL_R-KEY_L: CTRL-Tab
      ALT_R-KEY_H: CTRL-SHIFT-Tab
      ALT_R-KEY_J: ALT-SHIFT-Down
      ALT_R-KEY_K: ALT-SHIFT-Up
      ALT_R-KEY_L: CTRL-Tab
